export const restaurants = [
    {
        id:0,
        name:'Moxies Southlake',
        picture: 'https://www.southlaketownsquare.com/wp-content/uploads/2019/03/Moxies.jpg',
        website: 'https://moxies.com/restaurants/southlake?utm_source=GMB&utm_medium=google-location-listing&utm_campaign=organic',
        address: {
            street: "1472 Main Street, Southlake,",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:1,
        name:'Shuck Me',
        picture: 'https://www.shuckme.net/images/ShuckMe.jpg',
        website: 'https://www.shuckme.net/southlake-menu/',
        address: {
            street: "585 Randol Mill Ave",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:0,
        name:'Delucca',
        picture: 'https://i0.wp.com/havingfuninthetexassun.com/wp-content/uploads/2018/05/img_4719.jpg?fit=4032%2C3024&ssl=1',
        website: 'https://www.delucca.com/location/delucca-southlake/',
        address: {
            street: "2001 W Southlake Blvd #103",
            suite: "#103",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },    
    {
        id:0,
        name:'Moxies Southlake',
        picture: 'https://www.southlaketownsquare.com/wp-content/uploads/2019/03/Moxies.jpg',
        website: 'https://moxies.com/restaurants/southlake?utm_source=GMB&utm_medium=google-location-listing&utm_campaign=organic',
        address: {
            street: "1472 Main Street, Southlake,",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:1,
        name:'Shuck Me',
        picture: 'https://www.shuckme.net/images/ShuckMe.jpg',
        website: 'https://www.shuckme.net/southlake-menu/',
        address: {
            street: "585 Randol Mill Ave",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:0,
        name:'Delucca',
        picture: 'https://i0.wp.com/havingfuninthetexassun.com/wp-content/uploads/2018/05/img_4719.jpg?fit=4032%2C3024&ssl=1',
        website: 'https://www.delucca.com/location/delucca-southlake/',
        address: {
            street: "2001 W Southlake Blvd #103",
            suite: "#103",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:0,
        name:'Moxies Southlake',
        picture: 'https://www.southlaketownsquare.com/wp-content/uploads/2019/03/Moxies.jpg',
        website: 'https://moxies.com/restaurants/southlake?utm_source=GMB&utm_medium=google-location-listing&utm_campaign=organic',
        address: {
            street: "1472 Main Street, Southlake,",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:1,
        name:'Shuck Me',
        picture: 'https://www.shuckme.net/images/ShuckMe.jpg',
        website: 'https://www.shuckme.net/southlake-menu/',
        address: {
            street: "585 Randol Mill Ave",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:0,
        name:'Delucca',
        picture: 'https://i0.wp.com/havingfuninthetexassun.com/wp-content/uploads/2018/05/img_4719.jpg?fit=4032%2C3024&ssl=1',
        website: 'https://www.delucca.com/location/delucca-southlake/',
        address: {
            street: "2001 W Southlake Blvd #103",
            suite: "#103",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },    
    {
        id:0,
        name:'Moxies Southlake',
        picture: 'https://www.southlaketownsquare.com/wp-content/uploads/2019/03/Moxies.jpg',
        website: 'https://moxies.com/restaurants/southlake?utm_source=GMB&utm_medium=google-location-listing&utm_campaign=organic',
        address: {
            street: "1472 Main Street, Southlake,",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:1,
        name:'Shuck Me',
        picture: 'https://www.shuckme.net/images/ShuckMe.jpg',
        website: 'https://www.shuckme.net/southlake-menu/',
        address: {
            street: "585 Randol Mill Ave",
            suite: "",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    },
    {
        id:0,
        name:'Delucca',
        picture: 'https://i0.wp.com/havingfuninthetexassun.com/wp-content/uploads/2018/05/img_4719.jpg?fit=4032%2C3024&ssl=1',
        website: 'https://www.delucca.com/location/delucca-southlake/',
        address: {
            street: "2001 W Southlake Blvd #103",
            suite: "#103",
            city: "Southlake",
            state: 'Texas',
            zipcode: "76092",
        },
    }
];